### ISSUE TITLE
command not found: MitoGeneExtractor

### ISSUE THREAD

**Issue by avvypaks** [cmayer/MitoGeneExtractor#4]
Hi,

I am not able to run the program after installing it as you have instructed. My exonerate installation was successful. It's still showing:

zsh: command not found: MitoGeneExtractor

Could you please help me with this?

**Comment by marievalerie** [comment]
Did you try to execute MitoGeneExtractor with the full path?

This is required if you do not add the program to your PATH. If you cloned/downloaded MitoGeneExtractor from the GitHub repository, I would further expect that the executable has a version (1.9.5) number associated with it...

**Comment by cmayer** [comment]
On Linux/Mac Os you have the PATH variable that contains all directories that the system will look in to find the program. If the binary is not found in any of these directories, you will get this error message.
Even if the program binary is in your current working directory, you will need to use "./MiteGeneExtractor" to start the program, unless the directory "." is in the path.

Another potential cause for the error message is:
The makefile produces a binary with the name MitoGeneExtractor-v1.9.5 and not just MitoGeneExtractor.

**Comment by cmayer** [comment]
In the README, I added that the program name is MitoGeneExtractor-vx.y.z where x.y.z is the version number.
This should make it more clear.
Thanks.

**Comment by avvypaks** [comment]
It worked after putting it into PATH. Thanks

**Comment by avvypaks** [comment]
innovation_user@Innovation-08 MitoGeneExtractor-main % MitoGeneExtractor -q merged18.fastq -p F04translated.fasta -o out-alignment.fas -n 0 -c out-consensus.fas -t 0.5 -r 1 -C 5
Welcome to the MitoGeneExtractor program, version 1.9.5
WARNING: You did not specify a vulgar file, so a temporary vulgar file will be created for this run that will be removed at the end of this program run. Therefor the vulgar file cannot be reused in other runs.
Parameter settings:
===================
DNA fastq input file names:                             merged18.fastq
Protein reference input file name:                      F04translated.fasta
Directory for temporary files:                          .
Base name for alignment output file:                    out-alignment.fas
Vulgar file name:                                       tmp-vulgar.txt
Genetic code (NCBI genetic code number):                5
Print this number of bp beyond Exonerate alignment:     0
Write consensus sequence to file :                      yes
Filename for consensus sequence output:                 out-consensus.fas
Consensus sequence threshold value:                     0.5
Frameshift penalty:                                     -9
Relative score threshold:                               1
Minimum coverage in Exonerate alignment:                1
Minimum coverage in Exonerate alignment (upper case):   1
Gappy reads used:                                       yes
Frameshift reads used:                                  no
Treat all references as independent:                    no
Report gaps mode:                                       Report all (leading, trailing, internal) gaps with '-' character.
Verbosity:                                              1
===================
Filename:./Concatenated_exonerate_input_XXXXXX
Filename:./Concatenated_exonerate_input_XXXXXX
Filename:./Concatenated_exonerate_input_ZO3Ugq
The specified vulgar file exists, so it does not have to be recomputed with exonerate.
NOTE: Exonerate hit skipped due to low relative alignment score: 0.792982 396580ee-63da-4195-b01f-1cf01fcfc00f
NOTE: Exonerate hit skipped due to low relative alignment score: 0.764368 386f9be3-37d4-40d4-bbb7-6dd7d3ab8eb9
NOTE: Exonerate hit skipped due to low relative alignment score: 0.984848 63ade953-ffdf-4140-8a95-99fd8d23257c
WARNING: Vulgar file is incomplete. It does not end with "-- completed exonerate analysis"
This is attempt number 1 to read the vulgar file. I will try to recompute the vulgar file.
sh: line 1: 15994 Segmentation fault: 11  exonerate --geneticcode FFLLSSSSYY**CCWWLLLLPPPPHHQQRRRRIIMMTTTTNNKKSSSSVVVVAAAADDEEGGGG --frameshift -9 --query F04translated.fasta -Q protein --target ./Concatenated_exonerate_input_ZO3Ugq -T dna --model protein2dna --showalignment 0 --showvulgar 1 > tmp-vulgar.txt 2> tmp-vulgar.txt.log
sh: line 1: 15999 Segmentation fault: 11  exonerate --geneticcode FFLLSSSSYY**CCWWLLLLPPPPHHQQRRRRIIMMTTTTNNKKSSSSVVVVAAAADDEEGGGG --frameshift -9 --query F04translated.fasta -Q protein --target ./Concatenated_exonerate_input_ZO3Ugq -T dna --model protein2dna --showalignment 0 --showvulgar 1 > tmp-vulgar.txt 2> tmp-vulgar.txt.log
sh: line 1: 16001 Segmentation fault: 11  exonerate --geneticcode FFLLSSSSYY**CCWWLLLLPPPPHHQQRRRRIIMMTTTTNNKKSSSSVVVVAAAADDEEGGGG --frameshift -9 --query F04translated.fasta -Q protein --target ./Concatenated_exonerate_input_ZO3Ugq -T dna --model protein2dna --showalignment 0 --showvulgar 1 > tmp-vulgar.txt 2> tmp-vulgar.txt.log
sh: line 1: 16003 Segmentation fault: 11  exonerate --geneticcode FFLLSSSSYY**CCWWLLLLPPPPHHQQRRRRIIMMTTTTNNKKSSSSVVVVAAAADDEEGGGG --frameshift -9 --query F04translated.fasta -Q protein --target ./Concatenated_exonerate_input_ZO3Ugq -T dna --model protein2dna --showalignment 0 --showvulgar 1 > tmp-vulgar.txt 2> tmp-vulgar.txt.log
sh: line 1: 16009 Segmentation fault: 11  exonerate --geneticcode FFLLSSSSYY**CCWWLLLLPPPPHHQQRRRRIIMMTTTTNNKKSSSSVVVVAAAADDEEGGGG --frameshift -9 --query F04translated.fasta -Q protein --target ./Concatenated_exonerate_input_ZO3Ugq -T dna --model protein2dna --showalignment 0 --showvulgar 1 > tmp-vulgar.txt 2> tmp-vulgar.txt.log
sh: line 1: 16013 Segmentation fault: 11  exonerate --geneticcode FFLLSSSSYY**CCWWLLLLPPPPHHQQRRRRIIMMTTTTNNKKSSSSVVVVAAAADDEEGGGG --frameshift -9 --query F04translated.fasta -Q protein --target ./Concatenated_exonerate_input_ZO3Ugq -T dna --model protein2dna --showalignment 0 --showvulgar 1 > tmp-vulgar.txt 2> tmp-vulgar.txt.log
sh: line 1: 16015 Segmentation fault: 11  exonerate --geneticcode FFLLSSSSYY**CCWWLLLLPPPPHHQQRRRRIIMMTTTTNNKKSSSSVVVVAAAADDEEGGGG --frameshift -9 --query F04translated.fasta -Q protein --target ./Concatenated_exonerate_input_ZO3Ugq -T dna --model protein2dna --showalignment 0 --showvulgar 1 > tmp-vulgar.txt 2> tmp-vulgar.txt.log
sh: line 1: 16017 Segmentation fault: 11  exonerate --geneticcode FFLLSSSSYY**CCWWLLLLPPPPHHQQRRRRIIMMTTTTNNKKSSSSVVVVAAAADDEEGGGG --frameshift -9 --query F04translated.fasta -Q protein --target ./Concatenated_exonerate_input_ZO3Ugq -T dna --model protein2dna --showalignment 0 --showvulgar 1 > tmp-vulgar.txt 2> tmp-vulgar.txt.log
sh: line 1: 16021 Segmentation fault: 11  exonerate --geneticcode FFLLSSSSYY**CCWWLLLLPPPPHHQQRRRRIIMMTTTTNNKKSSSSVVVVAAAADDEEGGGG --frameshift -9 --query F04translated.fasta -Q protein --target ./Concatenated_exonerate_input_ZO3Ugq -T dna --model protein2dna --showalignment 0 --showvulgar 1 > tmp-vulgar.txt 2> tmp-vulgar.txt.log
sh: line 1: 16025 Segmentation fault: 11  exonerate --geneticcode FFLLSSSSYY**CCWWLLLLPPPPHHQQRRRRIIMMTTTTNNKKSSSSVVVVAAAADDEEGGGG --frameshift -9 --query F04translated.fasta -Q protein --target ./Concatenated_exonerate_input_ZO3Ugq -T dna --model protein2dna --showalignment 0 --showvulgar 1 > tmp-vulgar.txt 2> tmp-vulgar.txt.log
ERROR: Running exonerate failed. The generated vulgar file is incomplete and should be removed manually. Exiting.

MitoGeneExtractor says goodbye.



IT WOULD BE GREAT IF YOU CAN TELL ME WHAT THIS "Segmentation fault: 11" IS ALL ABOUT.

**Comment by cmayer** [comment]
The problem is that the exonerate program crashed.
Our experience is that a common reason for this problem is that the computer has insufficient RAM
to run exonerate. We could also try to analyse the data on one of our machines.

**Comment by avvypaks** [comment]
Thanks for the response. I will try with a server and let you know.

**Comment by cmayer** [comment]
The issue  command not found: MitoGeneExtractor #4 has been resolved.

**Comment by cmayer** [comment]
Dear avvypaks,

I would like to move this issue to a new issue. Users who look through the issues will not look for segmentation faults if the heading is "command not found: MitoGeneExtractor". 

By the way: Did you run MitoGeneExtractor on a server and did you get results from this?

**Comment by avvypaks** [comment]
Hi cmayer,

I am getting a different error while running to a linux server. Although the compilation of exonerate was successful, still the program was showing error that it can not make the vulgar file as exonerate is not there. I have tried to put the exonerate prog to my path of MitoGeneExtractor, but still no luck! I am working on a insect genome skim data, Is it possible to try your prog in another way ?

**Comment by marievalerie** [comment]
Hi,
unfortunately, you cannot run MGE without exonerate but I can hardly imagine that exonerate cannot be found if everything is set up properly.  Let's see if we can solve the issue :)

Could you please:
1.) post the MitoGeneExtractor command that produced the error and tell me which exonerate version you used.
2.) type ```ls```  followed by the /path/to/exonerate that you specified in 1.) and post the output (just to be sure, that there is no spelling mistake)

If it is not related to a simple spelling mistake, please check if the compilation of Exonerate was really successful. You can test that by typing ```/path/to/exonerate -h``` and you should see the help page of exonerate and all the options that you can specify.

In principle, if exonerate works, you can run it separately to produce the vulgar file. The vulgar file then, can be used by MGE. Let's see what Christoph suggests in that case.

Alternatively, you can share your data with me privately (m.brasseur@leibniz-lib.de) and I will have a look, if you want.

All the best,
Marie

**Comment by cmayer** [comment]
If you are running MitoGeneExtractor on a HPC cluster with a job system, the path is not automatically exported to the bash environment that runs the job. A simple work arround in this case is to use the -e parameter (in MitoGeneExtractor) to specify the full path to the exonerate program. 
Marie has also suggested to tun exonerte separately and specify the vulgar file that exonerate produces as an input to the MitoGeneExtractor program. 

Best,
Christoph
